# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5005d6175714703911bd4694de43ab708aa246475ac956b9ecf0900d4b7286a66826b90671e0de35116b756a32f958afd2d51e3a119950aa9541fd7d8b5cb6f9

test:
  secret_key_base: b4a8103041bba0dc05d34ca8856c0e1364ff4ad3fc1b4bf356443683f9bdf3086c45567a9cf043cdfca506a9cf973d75e021b639f5ec3f88e9cd5fa7e4dabdc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
